title: Adarsa Sivaprasad
email: adarsasprasad@gmail.com

#Everything from getting started with Data Science, natural langugae generation to midnight art.

description: > # this means to ignore newlines until "baseurl:"
  The synapse of the left and right brain and all the sparks in between.
show_excerpts: true # set to true to show excerpts on the homepage

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://adarsa.github.io" # the base hostname & protocol for your site, e.g. http://example.com
author:
  name: Adarsa
  picture: /assets/about/image1.jpg

github_username:  adarsa
linkedin_profile: adarsasprasad


# Build settings
#theme: minima #jekyll-theme-time-machine 
theme: jekyll-theme-basically-basic
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
feed:
  path: atom.xml

paginate: 10
paginate_path: /page:num/

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
  # _projects
  - scope:
      path: "_projects"
      type: projects
    values:
      layout: page
      read_time: false


# Exclude from processing.
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
